import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { BUSINESS_LEGAL_NAME, BUSINESS_NAME } from "@/lib/constants/business-contact";
import { drawNavyTopBanner } from "./stamp-completed";

export type CertificateInput = {
  requestId: string;
  documentName: string;
  sha256: string;
  createdAt: string;
  completedAt: string;
  originatorName: string;
  originatorEmail: string;
  signerName: string;
  signerEmail: string;
  viewedAt: string | null;
  viewedIp: string | null;
  signedAt: string;
  signedIp: string | null;
  certRef: string | null;
  signaturePng: Uint8Array;
};

function fmt(iso: string | null | undefined): string {
  if (!iso) return "—";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString("en-US", { timeZone: "America/New_York" });
}

export async function buildCertificatePdf(input: CertificateInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const helv = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  let logo: Awaited<ReturnType<PDFDocument["embedPng"]>> | null = null;
  try {
    logo = await doc.embedPng(await readFile(join(process.cwd(), "public/logo.png")));
  } catch {
    logo = null;
  }
  drawNavyTopBanner(page, logo, bold, "CERTIFICATE");
  const ink = rgb(0.06, 0.09, 0.16);
  const mute = rgb(0.35, 0.4, 0.48);
  let y = 720;

  page.drawText("Certificate of Completion", { x: 56, y, size: 20, font: bold, color: ink });
  y -= 18;
  page.drawText(BUSINESS_LEGAL_NAME, { x: 56, y, size: 11, font: helv, color: mute });
  y -= 28;

  const rows: [string, string][] = [
    ["Organization", BUSINESS_NAME],
    ["Document id", input.requestId],
    ["Document", input.documentName],
    ["SHA-256", input.sha256],
    ["Created on", fmt(input.createdAt)],
    ["Completed on", fmt(input.completedAt)],
    ["Originator", `${input.originatorName} <${input.originatorEmail}>`],
    ["Signer", `${input.signerName} <${input.signerEmail}>`],
    ["Viewed on", fmt(input.viewedAt)],
    ["Viewed IP", input.viewedIp || "—"],
    ["Signed on", fmt(input.signedAt)],
    ["Signed IP", input.signedIp || "—"],
    [
      "Authentication",
      `Email link · Ref ${input.certRef || "—"} · unique URL from the signer inbox`,
    ],
  ];

  for (const [label, value] of rows) {
    page.drawText(label, { x: 56, y, size: 8, font: bold, color: mute });
    const text = value.length > 92 ? `${value.slice(0, 89)}…` : value;
    page.drawText(text, { x: 56, y: y - 12, size: 9, font: helv, color: ink });
    y -= 32;
  }

  page.drawText("Signature", { x: 56, y, size: 8, font: bold, color: mute });
  y -= 8;
  const img = await doc.embedPng(input.signaturePng);
  const sigBoxW = 220;
  const sigBoxH = 48;
  const sigScale = Math.min(sigBoxW / img.width, sigBoxH / img.height);
  page.drawImage(img, {
    x: 56,
    y: y - sigBoxH + (sigBoxH - img.height * sigScale) / 2,
    width: img.width * sigScale,
    height: img.height * sigScale,
  });
  y -= 70;
  page.drawText(
    "Generated by DebtSupportPros CRM. Records the emailed signing link, timestamps,",
    { x: 56, y, size: 8, font: helv, color: mute }
  );
  page.drawText("IP address, and a SHA-256 hash of the locked signed form.", {
    x: 56,
    y: y - 12,
    size: 8,
    font: helv,
    color: mute,
  });
  y -= 36;
  page.drawText("Restrictions", { x: 56, y, size: 8, font: bold, color: mute });
  y -= 12;
  const restrictions = [
    "This is an electronic original. Do not alter the signed form after the Completed on time.",
    "Any change to the PDF after completion invalidates this certificate and the SHA-256 match.",
    "The signer was authenticated by opening a unique link sent only to their email.",
    "This record is intended to satisfy ESIGN Act / UETA electronic signature requirements.",
    "Keep this certificate with the signed document. Counsel should review before litigation use.",
  ];
  for (const line of restrictions) {
    page.drawText(line, { x: 56, y, size: 7.5, font: helv, color: ink });
    y -= 11;
  }

  return doc.save({ useObjectStreams: false });
}
